M48
; DRILL file {KiCad (6.0.0)} date Sun Feb 19 23:28:08 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-19T23:28:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0591
%
G90
G05
T1
X5.435Y-4.4591
X5.435Y-4.6866
T2
X5.2459Y-5.2402
X5.2459Y-5.3583
T3
X6.0787Y-4.2069
X6.0787Y-4.4825
T0
M30
